SEO-176838-URL-issue-page
syncfusion-content/asp.netwebforms-docs pull request #422
Opened 2023-11-01 13:09 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on page issue link,
Please review.
Thanks.

Regards,
Edith.

2023-11-01 13:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176838-URL--issue-page](https://jenkins.syncfusion.com/job/Content/job/asp.netwebforms-docs/303/console)**

2023-11-08 14:04 UTC, Yvone-Atieno requested changes
Commented

2023-11-08 14:04 UTC, Yvone-Atieno commented on aspnet/Overview.md
> +* The best way to get started is to read the common “[Getting Started](/aspnet/getting-started-webforms)” document of the component that you would like to start using first. The “Getting Started” gui
Revert this

2023-11-10 12:35 UTC, Edithabich commented on aspnet/Overview.md
> +* The best way to get started is to read the common “[Getting Started](/aspnet/getting-started-webforms)” document of the component that you would like to start using first. The “Getting Started” gui
reverted

2023-11-10 12:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176838-URL--issue-page](https://jenkins.syncfusion.com/job/Content/job/asp.netwebforms-docs/306/)<br/>**

2023-11-10 12:36 UTC, closed without merging