SEO-181471-ASPNET-HTTP-TO-HTTPS
syncfusion-content/asp.netwebforms-docs pull request #470
Opened 2024-04-04 13:46 UTC by Scholar-jaruha

Hi @MallikaRK,
I have fixed the http issues, please review.
Regards,
Scholar.

2024-04-04 13:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181471-ASPNET-HTTP-TO-HTTPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/18/console)**

2024-04-04 13:48 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/18/artifact/cireports/)<br/>Build Location: [SEO-181471-ASPNET-HTTP-TO-HTTPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/18/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/18/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/18/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/18/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/18/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [8](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/18/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/18/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/18/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/18/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-12 09:07 UTC, MallikaRK requested changes
commented

2024-04-12 09:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181471-ASPNET-HTTP-TO-HTTPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/20/console)**

2024-04-12 09:28 UTC, Scholar-jaruha commented on aspnet/TreeView/Checkboxes.md
> +description: Learn here about specifying checkboxes in Syncfusion ASPNET TreeView control, its settings and more.
changed

2024-04-12 09:38 UTC, MallikaRK approved these changes
approved

2024-04-22 10:35 UTC, Aishwarya-Ganesan approved these changes
fine.

2024-04-22 10:35 UTC, merged