SEO-18702-ASP.NET-Gantt-Exporting-Description-too-long
syncfusion-content/asp.netwebforms-docs pull request #520
Opened 2024-08-05 13:01 UTC by Faith-Atieno

Title | Description
-- | --
|Task Category | Site Audite|
|Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/asp.netwebforms-docs/pull/520|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187172|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BCE6E5440-7D4E-43FE-B673-E79BCD0BF05D%7D&file=Faith-Site%20Audit.xlsx&action=default&mobileredirect=true&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1722849150540&web=1|

Title | Description
-- | --
|Task Category | Site Audite|
|Content Task Link/Mail Scr
Changes made | Reason for change
-- | --
| Page with redirect| To increase page performance |

2024-08-05 13:01 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/96/console)**

2024-08-05 13:02 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/96/artifact/cireports/)<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/96/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [1](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/96/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/96/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/96/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/96/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/96/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/96/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/96/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/96/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-05 13:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/97/console)**

2024-08-05 13:09 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/97/artifact/cireports/)<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/97/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/97/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/97/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/97/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/97/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/97/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/97/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/97/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/97/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-05 13:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/98/console)**

2024-08-05 13:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/98/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/98/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/98/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/98/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/98/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/98/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/98/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/98/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/98/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-05 15:08 UTC, Yvone-Atieno requested changes
Commented

2024-08-05 15:08 UTC, Yvone-Atieno commented on aspnet/Gantt/Exporting.md
> +description: Learn here about Exporting with the Syncfusion ASP.NET Web Forms Gantt control, its elements, and more.
Change description - Learn here about exporting support in Syncfusion ASP.NET Web Forms Gantt control, its elements, and more.

2024-08-05 15:08 UTC, Yvone-Atieno commented on aspnet/Gantt/Exporting.md
> +# Exporting Sf ASP.NET Web Forms Gantt
Updated proper H1

2024-08-05 15:08 UTC, Yvone-Atieno commented on aspnet/Gantt/Exporting.md
> +![Export in ASP.NET Web Forms Gantt Exporting](Export_images/Export_img1.png)
Updated proper Alt

2024-08-06 06:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/99/console)**

2024-08-06 06:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/99/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/99/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/99/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/99/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/99/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/99/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/99/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/99/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/99/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-06 07:11 UTC, Yvone-Atieno commented on aspnet/Gantt/Exporting.md
> +# ASP.NET Gantt-Invokes export public method of Gantt object to export.
Update H1 as Exporting in ASP.NET Web Forms Gantt Control

2024-08-06 07:12 UTC, Yvone-Atieno commented on aspnet/Gantt/Exporting.md
> +![PDF exporting enabled in ASP.NET Web Forms Gantt Exporting](Export_images/Export_img1.png)
Update proper Alt

2024-08-06 07:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/console)**

2024-08-06 07:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-06 13:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-07 05:44 UTC, Yvone-Atieno requested changes
Commented

2024-08-07 05:44 UTC, Yvone-Atieno commented on aspnet/Gantt/Exporting.md
> +![PDF exporting enabled in ASP.NET Web Forms Gantt](Export_images/Export_img1.png)
Rename image also

2024-08-16 09:06 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/console)**

2024-08-16 09:06 UTC, SyncfusionBuild commented
The CI [Job](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/console) is already running for this Pull Request/Merge Approved with latest commit id. You cannot trigger the duplicate job for same.

2024-08-16 09:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/console)**

2024-08-16 09:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/100/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-19 13:39 UTC, Yvone-Atieno requested changes
Commented

2024-08-19 13:39 UTC, Yvone-Atieno commented on aspnet/Gantt/Exporting.md
> +# Exporting in ASP.NET Web Forms Gantt Control.
remove full stop

2024-08-19 13:39 UTC, Yvone-Atieno commented on aspnet/Gantt/Exporting.md
> +![Exporting in ASP.NET Web Forms Gantt Control](Export_images/Export_img1.png)
Added dot at the end of image Alt

2024-08-20 07:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/console)**

2024-08-20 07:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/101/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-13 07:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/225/console)**

2024-09-13 07:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/225/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/225/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/225/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/225/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/225/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/225/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/225/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/225/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/225/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-13 07:43 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/console)**

2024-09-13 07:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/console)**

2024-09-13 07:50 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/artifact/cireports/)<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/)<br/>Technical Error(s): [1](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/226/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-13 09:20 UTC, Faith-Atieno commented
![image](https://github.com/user-attachments/assets/19ffa5c3-05c3-447f-84c8-c91deaa95331)

2024-09-13 11:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/228/console)**

2024-09-13 11:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/229/console)**

2024-09-13 12:10 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/229/artifact/cireports/)<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/229/)<br/>Technical Error(s): [1](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/229/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/229/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/229/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/229/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/229/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/229/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/229/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/229/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/229/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-16 12:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/232/console)**

2024-09-16 12:22 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/232/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/232/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/232/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/232/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/232/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/232/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/232/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/232/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/232/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-16 13:46 UTC, Yvone-Atieno requested changes
Commented

2024-09-16 13:46 UTC, Yvone-Atieno commented on aspnet/Gantt/Exporting.md
> +description: Learn here all about exporting support in Syncfusion Essential ASP.NET Webforms Gantt Control, its elements, and more.
Use ASP.NET Web Forms instead of ASP.NET Webforms

2024-09-17 07:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-18702-ASP.NET-MVC-Gantt-Exporting-Description-too-long](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/236/console)**

2024-09-17 12:35 UTC, Yvone-Atieno approved these changes
Approved

2024-09-23 11:54 UTC, Aishwarya-Ganesan approved these changes
fine.

2024-09-23 11:54 UTC, merged