SEO-86912-webforms-redirect-links
syncfusion-content/asp.netwebforms-docs pull request #542
Opened 2024-08-21 14:57 UTC by Edithabich

Hi @Yvone-Atieno,

|Title|Description|
|--|--|
|Category|permanent redirect link |
|Hotfix PR|https://github.com/syncfusion-content/asp.netwebforms-docs/pull/537|
|Task||
|Content Ticket||
|UX Ticket||

|Changes made|Reason for changes|
|--|--|
|Changed redirect links|To avoid redirect link issues in the page and add direct link |

Regards,
Edith.

2024-08-21 14:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-86912-webforms-redirect-links](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/147/console)**

2024-08-21 15:07 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/147/artifact/cireports/)<br/>Build Location: [SEO-86912-webforms-redirect-links](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/147/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/147/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/147/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/147/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/147/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/147/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/147/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/147/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/147/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-22 09:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-86912-webforms-redirect-links](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/160/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/160/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/160/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/160/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/160/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/160/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/160/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/160/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/160/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-28 11:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-86912-webforms-redirect-links](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/187/console)**

2024-08-28 11:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-86912-webforms-redirect-links](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/187/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/187/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/187/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/187/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/187/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/187/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/187/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/187/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/187/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-28 13:16 UTC, Yvone-Atieno requested changes
Commented

2024-08-28 13:16 UTC, Yvone-Atieno commented on aspnet/SpreadSheet/Editing.md
> +description: Learn here about editing support in Syncfusion Essential ASP.NET Webforms Spreadsheet control, its elements and more details.
Update as Learn here about editing support in Syncfusion Essential ASP.NET Web Forms Spreadsheet control, its elements, and more details.

2024-08-29 14:46 UTC, Edithabich commented on aspnet/SpreadSheet/Editing.md
> +title: Editing in the ASP.NET Web Forms Spreadsheet Control | Syncfusion
resolved

2024-08-29 14:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-86912-webforms-redirect-links](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/193/console)**

2024-08-29 14:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-86912-webforms-redirect-links](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/193/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/193/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/193/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/193/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/193/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/193/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/193/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/193/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/193/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-05 06:26 UTC, Aishwarya-Ganesan approved these changes
fine.

2024-09-05 06:29 UTC, Yvone-Atieno approved these changes
Approved

2024-09-05 06:31 UTC, merged