SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS
syncfusion-content/asp.netwebforms-docs pull request #548
Opened 2024-08-23 08:39 UTC by Faith-Atieno

Title | Description
-- | --
|Task Category | Site Audit work|
|Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/asp.netwebforms-docs/pull/534|
|Ticket/Task link |https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187924|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B0C07BBB1-1233-47A7-818C-275A98FD0063%7D&file=Faith-%20Site%20Audit.xlsx&action=default&mobileredirect=true|

|Changes Made | Reason for change |
|-- | -- |
|Changed HTTP links to HTTPS | To avoid redirect links | 
|Modified H1, Description | to enhance user experience |
|Modified description | to improve user experience |  

2024-08-23 08:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/174/console)**

2024-08-23 08:41 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/174/artifact/cireports/)<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/174/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/174/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/174/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/174/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/174/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/174/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/174/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/174/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/174/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-23 08:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/175/console)**

2024-08-23 08:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/175/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/175/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/175/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/175/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/175/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/175/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/175/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/175/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/175/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-26 05:50 UTC, Yvone-Atieno requested changes
Commented

2024-08-26 05:50 UTC, Yvone-Atieno commented on aspnet/RichTextEditor/Validation.md
> +description: This article explains more about Validation to format the ASP.NET Web Forms RichTextEditor control's content
Check description

2024-08-26 05:50 UTC, Yvone-Atieno commented on aspnet/RichTextEditor/Validation.md
> +# ASP.NET Web Forms RichTextEditor Validation
Check H1

2024-08-26 06:32 UTC, Faith-Atieno commented on aspnet/RichTextEditor/Validation.md
> +description: This article explains more about Validation to format the ASP.NET Web Forms RichTextEditor control's content
resolved

2024-08-26 06:32 UTC, Faith-Atieno commented on aspnet/RichTextEditor/Validation.md
> +# ASP.NET Web Forms RichTextEditor Validation
resolved

2024-09-03 07:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/195/console)**

2024-09-03 07:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/195/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/195/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/195/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/195/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/195/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/195/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/195/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/195/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/195/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-03 13:22 UTC, Yvone-Atieno requested changes
Commented

2024-09-03 13:22 UTC, Yvone-Atieno commented on aspnet/RichTextEditor/Validation.md
> +description: This article explains more about Validation to format the ASP.NET Web Forms RichTextEditor control's content
Please check description

2024-09-17 09:40 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/238/console)**

2024-09-17 09:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/238/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/238/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/238/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/238/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/238/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/238/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/238/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/238/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/238/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-18 07:15 UTC, Yvone-Atieno requested changes
Commented

2024-09-18 07:15 UTC, Yvone-Atieno commented on aspnet/RichTextEditor/Validation.md
> +description: This article explains more about Validation to format the ASP.NET Web Forms RichTextEditor control's content
Updated title and description proper, this is not an article

2024-09-18 07:15 UTC, Yvone-Atieno commented on aspnet/RichTextEditor/Validation.md
> +# ASP.NET Web Forms RichTextEditor Validation
Update H1 as Validation  in  ASP.NET Web Forms RichTextEditor

2024-09-18 07:15 UTC, Yvone-Atieno commented on aspnet/RichTextEditor/Working-with-Tables.md
> +description: Learn here all about working with Tables in Syncfusion ASP.NET Web Forms RichTextEditor control, its elements, and more.
Learn here all about working with tables in Syncfusion ASP.NET Web Forms RichTextEditor control, its elements, and more.

2024-09-18 08:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/242/console)**

2024-09-18 08:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/242/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/242/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/242/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/242/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/242/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/242/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/242/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/242/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/242/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-18 12:16 UTC, Yvone-Atieno requested changes
Commented

2024-09-18 12:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/246/console)**

2024-09-18 12:25 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/246/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-09-18 12:25 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/246/)<br/>**

2024-09-18 12:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/247/console)**

2024-09-18 12:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/247/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/247/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/247/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/247/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/247/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/247/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/247/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/247/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/247/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-19 05:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/252/console)**

2024-09-19 05:57 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/252/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-09-19 05:57 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/252/)<br/>**

2024-09-19 05:58 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/253/console)**

2024-09-19 06:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/253/console)**

2024-09-19 06:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187924-ASP.NET-Web-Forms-RichTextEditor-Validation-HTTP-to-HTPPS](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/253/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/253/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/253/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/253/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/253/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/253/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/253/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/253/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/253/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-20 07:32 UTC, Yvone-Atieno approved these changes
Approved

2024-09-26 12:34 UTC, Aishwarya-Ganesan approved these changes
fine.

2024-09-26 12:34 UTC, merged