SEO-191916-ASP.NET-Daterangepicker
syncfusion-content/asp.netwebforms-docs pull request #565
Opened 2024-11-08 07:35 UTC by mercy-orejo

Hi @Yvone-Atieno  

|Title|Description|
|--|--|
|Task Category| Site Audit
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|Interlinking link|https://github.com/syncfusion-content/ej2-spreadsheet-angular-docs/pull/260|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/191916|
|Excel/SharePoint link| NA|

|Changes made|Reason for changes|
|--|--|
|Meta Title| Not relevant and too long exceeding 70 characters
|Meta Description| has duplicate words and not concise
|Meta h1|multiple h1 one tag in one page

Regards,
Mercy A.

2024-11-08 08:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-191916-ASP.NET-Dateranger-Site-audit](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/260/console)**

2024-11-08 08:08 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-191916-ASP.NET-Dateranger-Site-audit](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/260/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/260/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/260/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/260/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/260/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/260/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/260/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/260/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/260/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/260/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-08 08:16 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-191916-ASP.NET-Dateranger-Site-audit](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/261/console)**

2024-11-08 08:23 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/261/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-11-08 08:24 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-191916-ASP.NET-Dateranger-Site-audit](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/262/console)**

2024-11-08 08:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-191916-ASP.NET-Dateranger-Site-audit](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/262/console)**

2024-11-08 08:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-191916-ASP.NET-Dateranger-Site-audit](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/262/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/262/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/262/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/262/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/262/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/262/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/262/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/262/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/262/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/262/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-11 06:44 UTC, Yvone-Atieno requested changes
Commented

2024-11-11 07:30 UTC, mercy-orejo commented on aspnet/DatePicker/Display-Format.md
> +#  Formatting in ASP.NET DateRangePicker
Updated the correct title.

2024-11-11 07:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-191916-ASP.NET-Dateranger-Site-audit](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/263/console)**

2024-11-11 07:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-191916-ASP.NET-Dateranger-Site-audit](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/263/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/263/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/263/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/263/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/263/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/263/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/263/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/263/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/263/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/263/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-11 11:42 UTC, Yvone-Atieno requested changes
Commented

2024-11-11 11:42 UTC, Yvone-Atieno commented on aspnet/DatePicker/Display-Format.md
> +#  Formatting in ASP.NET Web Forms DatePicker
Remove extra space

2024-11-11 11:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-191916-ASP.NET-Dateranger-Site-audit](https://ci.syncfusion.com/job/Content/job/asp.netwebforms-docs/264/console)**

2024-11-11 12:36 UTC, closed without merging